services:

  database:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - rococo
    container_name: database
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -U ${POSTGRES_USER} -h localhost -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 10

#  migrator:
#    build:
#      context: ./migrator
#      dockerfile: ./Dockerfile
#    env_file:
#      - .env
#    networks:
#      - rococo
#    depends_on:
#      database:
#        condition: service_healthy
#    container_name: migrator

networks:
  rococo:
